services:
  mysql:
    image: mysql:8.0.36
    container_name: cloudobject_iq_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloudobjectiq_db
      MYSQL_USER: ciq_user
      MYSQL_PASSWORD: ciq_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  postgres:
    image: postgres:16.1
    container_name: cloudobject_iq_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudobjectiq_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  spark-master:
    image: apache/spark:3.5.1-python3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark_data:/opt/spark/data
      - .:/app
    restart: always

  spark-worker:
    image: apache/spark:3.5.1-python3
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8085:8081"
    volumes:
      - spark_data:/opt/spark/data
    depends_on:
      - spark-master
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: cloudobject_iq_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  mysql_data:
  postgres_data:
  spark_data:
  minio_data:

networks:
  cloudobject_iq_network:
    driver: bridge
